[workspace]
members = [
    "ch1",
    "ch3",
    "ch4",
    "homework_1",
    "homwork_2",
    "guessing_game",
    "ch5",
    "ch7",
    "ch8",
    "ch9",
    "ch10",
    "ch11",
    "ch12",
    "ch13",
    "ch14",
    "ch15",
    ]
